WorkFlow: # All key are Case Sensitive
  Driver: httpie  # default, httpie
  Order: true # If true all Crawler one after other in sequence | false will run simultaneously Not recommended as response output will be mangled
  Debug: false # non-default drivers will use it
# validations:   # Will soon add validations to type
  Crawler:
    - Scheme: https                               # The url Scheme (http or https)
      Method: GET                                 # Http method
      SSLVerify: false                            # To verify SSL certificate
      Auth:                                       # Auth if needed
        type: "basic"                             # As of now basic, digest, bearer
        Username: 'admin'                         # if basic or digest => Username AND Password are to be specified
        Password: 'pass'                          # if bearer => Token are to be specified
      Verbose: true                               # To see verbose request and response
      URL: 'httpbin.org/basic-auth/admin/pass'    # The URL without Scheme
    - Scheme: https
      Method: POST
      SSLVerify: false
      Auth:
        type: "bearer" # basic, digest, bearer
        Token: 'SomeTok' # Token
      Verbose: true
      URL: 'httpbin.org/post'
      Headers:                                    # Headders can be passed as list
        - Cookie: 'valued-visitor=yes;foo=bar'    # It should be in key value pairs
      PayLoad:                                    # The URL without Scheme
        json: ".\\testJson.json"                  # Absolute path (Recomended if not in same dir) of json file as string (Escape on windows)
    - Scheme: https
      Sessions:
        Runs: 1                                   # if default dirver is selected Mutiple session can be run
      Verbose: true
      Method: GET
      SSLVerify: false
      URL: httpie.io/hello
    - Scheme: http
      Method: GET
      Auth:
        type: "basic" # basic, digest, bearer
        Username: 'admin'
        Password: 'password' # Token
      SSLVerify: true
      URL: 'httpie.io/hello'
      Headers:
        - Cookie: 'valued-visitor=yes;foo=bar'
    - Scheme: https
      Method: POST
      SSLVerify: false
      Verbose: true
      URL: 'httpbin.org/post'
      Headers:
        - Cookie: 'valued-visitor=yes;foo=bar'
      PayLoad:
        json: ".\\testJson.json"   # Absolute path of json file as string (Escape on windows)
    - Scheme: https
      Sessions:
        Runs: 1
      Verbose: true
      Method: GET
      SSLVerify: false
      URL: httpie.io/hello

# http --auth=admin:password --verify=no GET http://httpie.io/hello Cookie:valued-visitor=yes;foo=bar @path